### ISSUE TITLE
ghc-prim dependency mismatch

### ISSUE THREAD

**Issue by fauno** [hvr/deepseq-generics#2]
the [package description](https://hackage.haskell.org/package/deepseq-generics-0.1.1.2/deepseq-generics.cabal) says it requires ghc-prim < 0.5 but the source says ghc-prim 0.4

**Comment by hvr** [comment]
What do you mean by "the source says ghc-prim 0.4"?

**Comment by fauno** [comment]
sorry i meant the [package description from source](https://github.com/hvr/deepseq-generics/blob/master/deepseq-generics.cabal#L45) says ghc-prim < 0.4

i ran into this issue while building pandoc 1.13.2.1 with ghc 7.10, since ghc provides base > 0.4 the build fails, but cabal didn't notice during source download because its database says ghc-prim requires base < 0.5

hope this is clearer

**Comment by hvr** [comment]
So this happens if you `cabal install deepseq-generics` too? Which `cabal-install` version are you using?

**Comment by fauno** [comment]
* cabal-install 1.22.2.0
* ghc 7.10.1 which provides ghc-prim 0.4.0.0

`cabal install deepseq-generics` works correctly (because deepseq-generics.cabal from hackage requires ghc-prim < 0.5), but `cabal fetch deepseq-generics` and `cabal build` on the extracted sources fails because `deepseq-generics.cabal` says ghc-prim < 0.4

**Comment by hvr** [comment]
Now I see; you should use `cabal get deepseq-generics` as that ones overlay the amended cabal revision into the extracted source folder. 

I'm still wondering; why do you operate manually on the source tarball, rather than using the revision-aware `cabal`-facilities?

**Comment by fauno** [comment]
Herbert Valerio Riedel <notifications@github.com> writes:

> Now I see; you should use `cabal get deepseq-generics` as that ones
> overlay the amended cabal revision into the extracted source folder.

cool, thanks!

> I'm still wondering; why do you operate manually on the source
>tarball, rather than using the revision-aware `cabal`-facilities?

because in order to distribute a pandoc binary package for parabola[0] i
need to provide a source tarball, so i use `cabal fetch` first, make a
source tarball and then build them using the distro pkgbuild[1]



[0]: https://parabola.nu
[1]: https://parabola.nu/packages/pcr/i686/pandoc-static/

-- 
http://hackcoop.com.ar

**Comment by dcoutts** [comment]
@fauno in that case I suggest that you make your tools patch the tarball with the latest .cabal file from the index. For example you could cabal unpack (which by default will update the .cabal file), and then call tar to make an updated tarball.

**Comment by fauno** [comment]
Duncan Coutts <notifications@github.com> writes:

> @fauno in that case I suggest that you make your tools patch the
> tarball with the latest .cabal file from the index. For example you
> could cabal unpack (which by default will update the .cabal file), and
> then call tar to make an updated tarball.

great! :)

-- 
http://hackcoop.com.ar

**Comment by fauno** [comment]
i solved it with `cabal get`, thanks!

**Comment by mimi1vx** [comment]
Isn't good problem solv ... not system ,

for example in rpm distributions is by default used cabal file from tar.gz  archive with bad constrains ...

please release new minor.minor version with updated cabal file .. 0.1.1.3 ..
